#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "librebooking"
name = "LibreBooking"
description.en = "Resource scheduling solution"
description.fr = "Solution de réservation des ressources"

version = "4.0.0~ynh1"

maintainers = ["DeMiro5001"]

[upstream]
license = "GPL-3.0"
admindoc = "https://librebooking.readthedocs.io"
code = "https://github.com/LibreBooking/app"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"

sso = "false"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/librebooking"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr_fr", "en_us"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]
    [resources.sources]

    [resources.sources.main]
        url = "https://github.com/LibreBooking/app/archive/refs/tags/v4.0.0.tar.gz"
        sha256 = "c75e2bca3a61c66cab74a0dc53b05d36bc912baeca75b5f97ef9900a0612e30f"

        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.4-pdo, php8.4-mbstring, php8.4-openssl, php8.4-tokenizer, php8.4-json, php8.4-curl, php8.4-xml, php8.4-ctype, php8.4-bcmath, php8.4-fileinfo  mariadb-server"

    [resources.database]
    type = "mysql"
