#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
admin_mail=$(ynh_user_get_info --username=$admin --key=mail)
admin_name=$(ynh_user_get_info --username=$admin --key=fullname)
timezone=$(ynh_app_setting_get --key=timezone)

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================

ynh_safe_rm $install_dir/tpl_c
mkdir $install_dir/tpl_c

chown "$app:www-data" "$install_dir/tpl_c"

ynh_config_add --template="config.dist.php" --destination="$install_dir/config/config.php"

chmod 600 "$install_dir/config/config.php"
chown "$app:www-data" "$install_dir/config/config.php"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
