#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

admin_mail=$(ynh_user_get_info --username=$admin --key=mail)
admin_name=$(ynh_user_get_info --username=$admin --key=fullname)

timezone="$(timedatectl show --value --property=Timezone)"
ynh_app_setting_set --key=timezone --value=$timezone

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set --key=php_upload_max_filesize --value=50M
ynh_app_setting_set --key=php_post_max_size --value=50M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

ynh_composer_exec install

mkdir $install_dir/tpl_c

chown -R "$app:www-data" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config.dist.php" --destination="$install_dir/config/config.php"

chmod 600 "$install_dir/config/config.php"
chown "$app:www-data" "$install_dir/config/config.php"

mkdir -p $data_dir/uploads/reservation
mkdir -p $data_dir/uploads/images
chown -R "$app:www-data" "$data_dir"
mkdir "/var/log/$app"
chown "$app:$app" "/var/log/$app"

ynh_config_add --template="librebooking.sql" --destination="$install_dir/database_schema/librebooking.sql"

ynh_mysql_db_shell < $install_dir/database_schema/librebooking.sql

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_logrotate

#ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
